# Generated by Django 5.0.3 on 2024-04-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_full_name_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
    ]
